### ISSUE TITLE
코드를 보면서..

### ISSUE THREAD

**Issue by khw7096** [redbean/LXIYM_myself#1]
git 관련 bat파일은 추후 git에 익숙해지면 아마 스스로 지울 스크립트일지도.. ^^;;
프로젝트별로 repository를 만드는게 좋아요.
왜냐하면.. 재밌을것 같은것은 저도 git clone 하는데.. 다른 소스들도 따라오는건 원하지 않거든요.~!
저도 과거에 이런 형태의 이것 저것 모으는 repository를 만들었지만 결국 분리해버린 2번의 기억이 있어요.

**Comment by kybin** [comment]
한웅씨 말과는 상관 없는 내용이지만.. ㅎㅎㅎ.
윈도우즈에서 깃을 쓰신다면 git bash를 써보세요.
cmd보다는 역시 훨씬 좋아요. 
bash 스크립트가 작성하기도 더 편하구요.

**Comment by redbean** [comment]
아항.. 넵 두분 감사합니다.ㅋㅋㅋ
아침에 보고 메세지 와있어서 깝놀 했어요 ...이렇게 글 많은건 처음인듯
